### ISSUE TITLE
com.lihaoyi:cask_2.12:0.3.6 in maven?

### ISSUE THREAD

**Issue by iamdionysus** [lihaoyi/cask#22]
The most recent version for scala 2.12 as of 2019-12-10 seems 0.2.9. Do you have any plan to update?

https://search.maven.org/artifact/com.lihaoyi/cask_2.12/0.2.9/jar

**Comment by lihaoyi** [comment]
No current plans, but if someone wants to contribute the necessary changes to cross-build the codebase I'll happily merge it
