### ISSUE TITLE
[Question] Async support

### ISSUE THREAD

**Issue by dhet** [lihaoyi/cask#37]
First of all, thanks @lihaoyi for your work on this library. There have been discussions in my team whether we should drop Akka HTTP in favor of something more simple, and Cask looks very promising in this regard.

Before jumping into prototyping I have a question: The docs mention that cask intentionally does not support async as means to keep the library simple. I'm wondering, what does this mean exactly?
* Does this mean that request processing is blocking, i.e. it can only handle one request at a time?
* How should you deal with async route logic, like accessing a database using a library that returns Futures?

**Comment by jodersky** [comment]
Good questions!

> Does this mean that request processing is blocking, i.e. it can only handle one request at a time?

The blocking part is correct, a route method will be processed by one thread. Note however that this thread is from a threadpool of configurable size and dynamics used by [undertow listeners](https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#listeners). This means that although individual requests are blocking, they are processed concurrently within the limits chosen by the threadpool.

> How should you deal with async route logic, like accessing a database using a library that returns Futures?

The simplest solution would probably be to use [scala.concurrent.Await](https://www.scala-lang.org/api/current/scala/concurrent/Await$.html) in your routes. You can still combine your futures the usual way and run them on a dedicated threadpool if you like, and only use a single Await in the route.

I've been a long-time user of cask myself and have never had any issues with its blocking design. In fact, the blocking design makes it extremely easy to debug and I would say increases my development speed.

**Comment by jodersky** [comment]
Good questions!

> Does this mean that request processing is blocking, i.e. it can only handle one request at a time?

The blocking part is correct, a route method will be processed by one thread. Note however that this thread is from a threadpool of configurable size and dynamics used by [undertow listeners](https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#listeners). This means that although individual requests are blocking, they are processed concurrently within the limits chosen by the threadpool.

> How should you deal with async route logic, like accessing a database using a library that returns Futures?

The simplest solution would probably be to use [scala.concurrent.Await](https://www.scala-lang.org/api/current/scala/concurrent/Await$.html) in your routes. You can still combine your futures the usual way and run them on a dedicated threadpool if you like, and only use a single Await in the route.

I've been a long-time user of cask myself and have never had any issues with its blocking design. In fact, the blocking design makes it extremely easy to debug and I would say increases my development speed.

**Comment by dhet** [comment]
Thanks for the clarification @jodersky, that does help a lot.

I agree with your statement about Await. There have been discussions about this very topic within our team. The docs seem to suggest that Await is to be avoided at all costs when in reality there are more than enough valid reasons to use it. For example in the case that a Future is guaranteed to be completed then using Await does no harm at all.

**Comment by lihaoyi** [comment]
@dhet @jodersky is largely correct. Each HTTP request is currently single-threaded, but you can have a thread pool to run 10 100 or 1,000 requests in parallel. You won't be able to run 1,000,000 concurrent requests, but most people don't need to.

If you really want totally-async HTTP requests, I would be open to a patch that implements that. Likely you will need to duplicate all the current `@cask.foo` decorators to `@cask.fooAsync` with different implementations, and maybe add some small tweaks to `cask.Main` to special case these (we already have a bit of special casing for `@cask.websocket` for example). Not totally trivial, but not terribly difficult either.

If you're Dropbox managing 1,000,000 long-polling HTTP clients per web-server, then Cask's thread-per-request model will not scale for you. If you're anyone else, 10 or 100 or 1,000 threads handling requests in parallel is plenty

**Comment by yamin-oanda** [comment]
Hi, with the upcoming JDK 19 virtual threads, I'm thinking of doing a small experiment to swap out the current Cask thread pool with an unbounded virtual thread pool. Am I correct in my reading of the code that the way to swap in this new thread pool would be something like:

```scala
import java.util.concurrent.Executors
import scala.concurrent.ExecutionContext

object MyCaskApp extends cask.MainRoutes {
  override def createExecutionContext =
    ExecutionContext.fromExecutorService(Executors.newVirtualThreadPerTaskExecutor()

  @cask.get("/")
  def hello() = "Hello, World!"
}
```

**Comment by jodersky** [comment]
Hi! 

I think it will be a little bit more involved. The `createExecutionContext` method is used for the threadpool that will underpin the actor context used for async requests such as websockets. If you want to change the execution environment of the HTTP request handling, you would need to look at how undertow does it. Undertow is the webserver backing cask (you can think of cask as a really nice glue layer that translates idiomatic scala to an undertow handler.

I'm not sure how you can configure undertow, but maybe it is helpful to look at the contact points between undertow and cask:
- the "handler" code: https://github.com/com-lihaoyi/cask/blob/d5fa6d47da5ea99d94887fafd555696ba07aa205/cask/src/cask/main/Main.scala#L49
- the undertow server setup code: https://github.com/com-lihaoyi/cask/blob/d5fa6d47da5ea99d94887fafd555696ba07aa205/cask/src/cask/main/Main.scala#L63-L70

**Comment by yamin-oanda** [comment]
Thanks for the pointer! I think I got it working, more tests required of course. But the basic change is, roughly,

```scala
// cask/cask/src/cask/Main.scala

object Main{
  class DefaultHandler(
    dispatchTrie: DispatchTrie[Map[String, (Routes, EndpointMetadata[_])]],
    mainDecorators: Seq[Decorator[_, _, _]],
    debugMode: Boolean,
    handleNotFound: () => Response.Raw,
    handleMethodNotAllowed: () => Response.Raw,
    handleError: (Routes, EndpointMetadata[_], Result.Error) => Response.Raw,
    // +++ Pass in the same executor service that is created in `class Main`:
    executionContext: ExecutionContextExecutorService)(implicit log: Logger) extends HttpHandler {

    // Dispatch the handler immediately to the executor service
    // As per https://undertow.io/undertow-docs/undertow-docs-2.1.0/undertow-handler-guide.html
    def handleRequest(exchange: HttpServerExchange): Unit = exchange.dispatch(executionContext, new Runnable {
      def run(): Unit = try {...
```

In the 'Undertow Handler Authors Guide' linked above, it is mentioned that:

> The root handler can return after HttpServerExchange.dispatch() has been called, or after async IO has been started...In this case the dispatched task will be submitted to the dispatch executor,...the exchange will not be finished, it is up to your async task to finish the exchange when it is done processing.

Which I believe Cask is indeed finishing the exchange i.e. closing and flushing the response when it is done.

**Comment by yamin-oanda** [comment]
So I did a little more testing and in short, virtual threads help when there is CPU-bound work (simulated using `Thread.sleep`), but they perform a little worse than the fixed thread pool when there is I/O-bound work. I suspect the JDK19 implementation of automatic async I/O still needs tuning and improvement. But, exciting times ahead. I'll send a small PR with the above changes.
