### ISSUE TITLE
HTTPS?

### ISSUE THREAD

**Issue by Seitzal** [lihaoyi/cask#7]
It would be nice if cask had some built-in way of encrypting communications via TLS / HTTPS.

**Comment by vitaliis** [comment]
TLS with various versions, cyphers, etc is a big and complex topic on its own.
I think cask is supposed to stay minimalistic and should not include such a topic.
I would suggest to use nginx or similar proxy to offload SSL traffic.

**Comment by lihaoyi** [comment]
yeah I'm gonna call this a wontfix.
