### ISSUE TITLE
Failing to run helloworld app minimalApplication-0.1.9 on macOS 10.13.6, scala 2.12.2

### ISSUE THREAD

**Issue by xraybat** [lihaoyi/cask#8]
macOS 10.13.6, unzipped minimalApplication-0.1.9 and cd-ed into folder, then,
```
$ ./cask -w app.runBackground
Error: Could not find or load main class Documents.Development.Scala.cask.minimalApplication-0.1.9.out.mill-cask
```
out/ folder contains mill-cask file and that's it, while
```
$ scala -version
Scala code runner version 2.12.2 -- Copyright 2002-2017, LAMP/EPFL and Lightbend, Inc.
```
thoughts?

**Comment by lihaoyi** [comment]
Can you try again on `0.3.0`? I think this should have been fixed

**Comment by xraybat** [comment]
yes, working now on macOS 10.14.6 / scala 2.13.0

thanks.
