### ISSUE TITLE
uPickle 0.7.1 compatibility

### ISSUE THREAD

**Issue by gavares** [lihaoyi/cask#9]
Cask version 0.1.9 throws runtime exceptions when used with uPickle 0.7.1. Exception is:

ClassNotFoundException: uJson.Visitor

**Comment by lihaoyi** [comment]
Yeah uPickle 0.7.1 is binary incompatible with the earlier releases, just need to build cask with the latest version. Send a PR!

**Comment by gavares** [comment]
Done. See #4
